<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>To Do - Backbone App</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="css/style.css">
        <script data-main="js/main" src="js/libs/require/require.js"></script>
    </head>
    <body>
    <div id="container">
        <div id="logo">
            <h1>To Do - Backbone.js Application</h1>
        </div>

        <div id="page">
            Loading...
        </div>

        <div id="footer"></div>
    </div>
    </body>
</html>
